# Generated by Django 4.2.6 on 2023-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='mailing_status',
            field=models.CharField(choices=[('failed', 'не отправлено'), ('excellent', 'отправлено')], max_length=50, verbose_name='статус попытки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='preferred_weekday',
            field=models.CharField(blank=True, choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], max_length=11, null=True, verbose_name='день недели'),
        ),
    ]
