# Generated by Django 4.2.6 on 2023-10-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_logs_mailing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='mailing_status',
            field=models.CharField(choices=[('created', 'Создана'), ('running', 'Запущена'), ('mailing', 'Идет отправка'), ('completed', 'Завершена')], default='created', max_length=150, verbose_name='статус рассылки'),
        ),
    ]
