# Generated by Django 4.2.6 on 2023-10-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='содержимое статьи')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение')),
                ('views_count', models.IntegerField(verbose_name='количество просмотров')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='признак публикации')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
            },
        ),
    ]
